import test from 'node:test';
import assert from 'node:assert/strict';
import {addCapacity} from '../src/capacity-whatif.js';
import {runReleaseWhatIf} from '../src/release-whatif.js';
import {forecastLots} from '../src/fab-analytics.js';
const fixture=()=>({nodes:[{desc:'ETCH',fab:'R3',equipment:{R3:{primary:['T1'],backup:[]}}},{desc:'OUT',fab:'R3'}],routes:[{id:'R01'}],equipment:[{id:'T1',role:'primary',availability:'READY',demoSlots:1,maintenance:[]}],timingStats:[{key:'T1|ETCH|MAIN',equipment_id:'T1',oper_desc:'ETCH',lot_type:'MAIN',count:10,median_sec_per_wafer:6000}],lots:Array.from({length:8},(_,i)=>({id:'L'+i,route:0,lot_type:'MAIN',fab:'R3',WF_QTY:25,path:[0,1],events:[[10000,0,0]],equipmentByStep:['T1',null]}))});
test('capacity clones one dedicated slot and timing without mutating source',()=>{const d=fixture(),before=JSON.stringify(d),r=addCapacity(d,0,2);assert.equal(r.data.equipment.length,3);assert.equal(r.data.equipment[1].demoSlots,1);assert.equal(r.data.timingStats[1].median_sec_per_wafer,6000);assert.equal(JSON.stringify(d),before);});
test('optimization compares equal inputs and detects constrained capacity improvement',()=>{const d=fixture(),before=JSON.stringify(d);const r=runReleaseWhatIf(d,{mode:'optimization',count:'0',days:'3',route_id:'R01',add_tools:'2',target_node:'0'});const base=r.scenarios[0],extra=r.scenarios.find(s=>s.target?.added===2);assert.ok(extra.completed>base.completed);assert.ok(extra.waitSaved>0);assert.equal(extra.completed+extra.wip,8);assert.equal(JSON.stringify(d),before);assert.throws(()=>runReleaseWhatIf(d,{mode:'optimization',count:'0',days:'3',route_id:'R01',add_tools:'99'}));});
test('remaining recovery override affects future jobs only',()=>{const d=fixture();d.equipment[0].availability='DOWN';const blocked=forecastLots(d),restored=forecastLots(d,{recoveryHours:12});assert.equal(blocked.predictions[0].events.length,0);const starts=restored.predictions.flatMap(p=>p.events.filter(e=>e[2]===1));assert.ok(starts.length>0);assert.ok(starts.every(e=>e[0]>=10080+720));assert.throws(()=>forecastLots(d,{recoveryHours:-1}));});
