export const managedFields=['lots','codes','fabs','operations','equipment'];
export function normalizeManaged(input,data){
 const result={};const catalogs={lots:data.lots.map(l=>l.id),codes:data.lots.map(l=>l.code),fabs:data.fabs,operations:data.nodes.flatMap(n=>[n.desc,n.operId]),equipment:data.equipment.map(e=>e.id)};
 for(const key of managedFields){const values=Array.isArray(input[key])?input[key]:String(input[key]||'').split(/[,\n]/);result[key]=[...new Set(values.map(v=>String(v).trim().toUpperCase()).filter(Boolean))];if(result[key].length>100)throw Error('항목별 최대 100개입니다.');const valid=new Set(catalogs[key].filter(Boolean).map(v=>v.toUpperCase()));for(const v of result[key])if(!valid.has(v))throw Error(`${key}: '${v}'는 현재 데이터에 없습니다.`);}
 return result;
}
export function matchesManaged(lot,state,nodes,filter){
 if(!filter)return true;const has=(k,v)=>!filter[k]?.length||filter[k].includes(String(v||'').toUpperCase());
 if(!has('lots',lot.id)||!has('codes',lot.code))return false;
 if(!state)return !['fabs','operations','equipment'].some(k=>filter[k]?.length);
 const n=nodes[state.node];return has('fabs',n?.fab)&&(!filter.operations?.length||has('operations',n?.desc)||has('operations',n?.operId))&&has('equipment',state.nextNode==null&&state.event[2]!==5?lot.equipmentByStep?.[state.event[1]]:null);
}
export function initManagedFavorites({data,current,apply}){
 const key='fab-managed-favorites-v1',section=document.createElement('section');section.id='managed-favorites';document.querySelector('#sidebar>.sidebar-heading').after(section);
 section.innerHTML='<div class="managed-heading"><strong>★ 내 관리 즐겨찾기</strong><button id="managed-edit">설정</button></div><div id="managed-list"></div><p id="managed-status" role="status">브라우저 로컬 저장 · 계정 동기화 아님</p><form id="managed-form" hidden><label>이름<input name="name" required maxlength="40" placeholder="예: R3 계측 관리"></label><p>같은 항목은 OR, 항목 사이는 AND. 여러 값은 쉼표로 구분합니다.</p>'+managedFields.map((k,i)=>'<label>'+['LOT ID','LOT CODE','FAB','공정명 / OPER ID','장비 ID'][i]+'<input name="'+k+'" placeholder="비우면 전체" list="managed-options-'+k+'"><datalist id="managed-options-'+k+'"></datalist></label>').join('')+'<button type="submit">저장하고 적용</button><button type="button" id="managed-clear">즐겨찾기 조건 해제</button></form>';
 const form=section.querySelector('form'),status=section.querySelector('#managed-status');section.querySelector('.managed-heading').append(section.querySelector('#managed-clear'));section.querySelector('#managed-clear').textContent='해제';let entries=[];try{const parsed=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(parsed))entries=parsed.filter(e=>e&&typeof e.name==='string'&&e.filter&&typeof e.filter==='object').slice(0,20);}catch{}
 const persist=()=>localStorage.setItem(key,JSON.stringify(entries));
 const use=entry=>{try{const f=normalizeManaged(entry.filter,data());apply(f,entry.base);status.textContent='적용: '+entry.name+' · 다른 화면 필터와 함께 적용';}catch(e){status.textContent=e.message;}};
 function render(){const list=section.querySelector('#managed-list');list.replaceChildren();for(const entry of entries){const row=document.createElement('div'),button=document.createElement('button'),remove=document.createElement('button');button.textContent=entry.name;button.onclick=()=>use(entry);remove.textContent='×';remove.setAttribute('aria-label',entry.name+' 즐겨찾기 삭제');remove.onclick=()=>{const previous=entries;entries=entries.filter(e=>e!==entry);try{persist();render();status.textContent='즐겨찾기 삭제 · 현재 적용 조건은 유지됩니다.';}catch(e){entries=previous;status.textContent='저장 실패';}};row.append(button,remove);list.append(row);}}
 section.querySelector('#managed-edit').onclick=()=>{form.hidden=!form.hidden;if(form.hidden)return;const d=data();if(!d){status.textContent='데이터 로딩 중';return;}const c=current();for(const k of managedFields)form.elements[k].value=(c.filter?.[k]||[]).join(', ');const catalogs={lots:d.lots.map(l=>l.id),codes:d.lots.map(l=>l.code),fabs:d.fabs,operations:d.nodes.flatMap(n=>[n.desc,n.operId]),equipment:d.equipment.map(e=>e.id)};for(const k of managedFields){const dl=section.querySelector('#managed-options-'+k);dl.replaceChildren();for(const value of new Set(catalogs[k].filter(Boolean))){const o=document.createElement('option');o.value=value;dl.append(o);}}};
 form.onsubmit=e=>{e.preventDefault();try{const name=form.elements.name.value.trim();if(!name)throw Error('이름을 입력하세요.');const f=normalizeManaged(Object.fromEntries(managedFields.map(k=>[k,form.elements[k].value])),data());const entry={name,filter:f,base:current().base},next=entries.filter(e=>e.name!==name);if(next.length>=20)throw Error('최대 20개까지 저장할 수 있습니다.');next.push(entry);localStorage.setItem(key,JSON.stringify(next));entries=next;render();use(entry);form.hidden=true;}catch(error){status.textContent=error.message;}};
 section.querySelector('#managed-clear').onclick=()=>{apply(null);status.textContent='즐겨찾기 조건 해제 · 기존 화면 필터는 유지';};render();
}
